SET(TARGET_DIR ".")

INCLUDE_DIRECTORIES(${BOOST_DIR}/include)
LINK_DIRECTORIES(${BOOST_DIR}/lib)

# ADD_DEFINITIONS(-DNOMINMAX)
# ADD_DEFINITIONS(-D_CRT_SECURE_NO_WARNINGS)

FILE(GLOB_RECURSE PUBLIC_HEADERS "src/*.h")

FILE(GLOB_RECURSE SOURCE_FILES "src/*.cpp" )

IF(%PROJ_PREFIX%_STATIC_BUILD)
	ADD_SUBDIRECTORY(static)
ELSE()
	ADD_SUBDIRECTORY(shared)
ENDIF()