SET(TARGET_NAME "%TARGET_NAME%")

ADD_DEFINITIONS(-D%PROJ_PREFIX_UPPER%_%LIB_NAME_UPPER%_LIB)

ADD_MSVC_PRECOMPILED_HEADER("%LIB_NAME_LOWER%_precomp.h" "%LIB_NAME_LOWER%_precomp.cpp" SOURCE_FILES)

ADD_LIBRARY (${TARGET_NAME} SHARED ${PUBLIC_HEADERS} ${SOURCE_FILES})

TARGET_LINK_LIBRARIES(${TARGET_NAME} ${FLAVOR_LIBS} ${BOOST_LIBS})

INSTALL(TARGETS ${TARGET_NAME}
	RUNTIME DESTINATION ${TARGET_DIR}
	LIBRARY DESTINATION ${TARGET_DIR})
	# ARCHIVE DESTINATION ${TARGET_DIR}/lib)

# Install the pdb if applicable:
#INSTALL_PDB()
