SET(TARGET_NAME "%TARGET_NAME%_static")

ADD_DEFINITIONS(-D%PROJ_PREFIX_UPPER%_LIB_STATIC)

ADD_MSVC_PRECOMPILED_HEADER("%LIB_NAME_LOWER%_precomp.h" "%LIB_NAME_LOWER%_precomp.cpp" SOURCE_FILES)

ADD_LIBRARY (${TARGET_NAME} ${PUBLIC_HEADERS} ${SOURCE_FILES})

TARGET_LINK_LIBRARIES(${TARGET_NAME} ${FLAVOR_LIBS} ${BOOST_LIBS})

